forge "http://forge.puppetlabs.com"

# Modules from the Puppet Forge
mod "puppetlabs/git"
mod "puppetlabs/ruby"
mod "puppetlabs/inifile"
mod "zack/r10k"
mod "puppetlabs/ntp"

mod "role", :git => "https://github.com/cpitman/puppetmaster-openstack-roles.git"

mod "apache", :git => "https://github.com/puppetlabs/puppetlabs-apache.git"
mod "ceilometer", :git => "https://github.com/stackforge/puppet-ceilometer.git"
mod "certmonger", :git => "https://github.com/rcritten/puppet-certmonger.git"
mod "cinder", :git => "https://github.com/stackforge/puppet-cinder.git"
mod "concat", :git => "https://github.com/ripienaar/puppet-concat.git"
mod "firewall", :git => "https://github.com/puppetlabs/puppetlabs-firewall.git"
mod "glance", :git => "https://github.com/stackforge/puppet-glance.git"
mod "haproxy", :git => "https://github.com/puppetlabs/puppetlabs-haproxy.git"
mod "heat", :git => "https://github.com/stackforge/puppet-heat.git"
mod "horizon", :git => "https://github.com/stackforge/puppet-horizon.git"
mod "inifile", :git => "https://github.com/puppetlabs/puppetlabs-inifile.git"
mod "memcached", :git => "https://github.com/saz/puppet-memcached.git"
mod "mongodb", :git => "https://github.com/puppetlabs/puppetlabs-mongodb.git"
mod "mysql", :git => "https://github.com/packstack/puppetlabs-mysql.git"
mod "neutron", :git => "https://github.com/stackforge/puppet-neutron.git"
mod "nova", :git => "https://github.com/stackforge/puppet-nova.git"
mod "nssdb", :git => "https://github.com/rcritten/puppet-nssdb.git"
mod "openstack", :git => "https://github.com/stackforge/puppet-openstack.git"
mod "pacemaker", :git => "https://github.com/radez/puppet-pacemaker.git"
mod "qpid", :git => "https://github.com/dprince/puppet-qpid"
mod "rsync", :git => "https://github.com/puppetlabs/puppetlabs-rsync.git"
mod "ssh", :git => "https://github.com/saz/puppet-ssh.git"
mod "stdlib", :git => "https://github.com/puppetlabs/puppetlabs-stdlib.git"
mod "swift", :git => "https://github.com/stackforge/puppet-swift.git"
mod "sysctl", :git => "https://github.com/puppetlabs/puppetlabs-sysctl.git"
mod "tempest", :git => "https://github.com/stackforge/puppet-tempest.git"
mod "vcsrepo", :git => "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
mod "vlan", :git => "https://github.com/derekhiggins/puppet-vlan.git"
mod "vswitch", :git => "https://github.com/stackforge/puppet-vswitch.git"
mod "xinetd", :git => "https://github.com/puppetlabs/puppetlabs-xinetd.git"
mod "rabbitmq", :git => "https://github.com/puppetlabs/puppetlabs-rabbitmq.git"
mod "staging", :git => "https://github.com/nanliu/puppet-staging.git"
mod "gluster", :git => "https://github.com/purpleidea/puppet-gluster.git"
mod "common", :git => "https://github.com/purpleidea/puppet-common.git"
mod "puppet", :git => "https://github.com/purpleidea/puppet-puppet.git"
mod "galera", :git => "https://github.com/rohara/puppet-galera.git"
mod "module-data", :git => "https://github.com/ripienaar/puppet-module-data"
mod "sahara", :git => "https://github.com/stackforge/puppet-sahara.git"
mod "keystone", :git => "https://github.com/stackforge/puppet-keystone.git"